apiVersion: v1
kind: Service
metadata:
  name: remote-dist2
spec:
  ports:
  - port: 8081
    name: tcp1
    targetPort: 8081
  - port : 2010
    name: tcp2
    targetPort: 2010
  selector:
    app: remote-dist2
  type: LoadBalancer
