apiVersion: apps/v1
kind: Deployment
metadata:
  name: remote-dist
  labels:
    app: remote-dist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remote-dist
  template:
    metadata:
      labels:
        app: remote-dist
    spec:
      nodeSelector:
        placement: cloud
      containers:
      - name: remote-dist
        image: docker.io/robertovrf/remote-dist:all
        imagePullPolicy: Always
        ports:
        - containerPort: 2011
        - containerPort: 2010
